name: Build

on:
  push:
    branches:
      - '*'
  schedule:
    - cron:  '0 4 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
            node-version: 18

      - name: End to end test
        id: e2e-test
        run: |
          yarn install
          yarn run check
